
package proyecto.view;

import proyecto.controller.MainMenuController;

public class MainMenuView extends javax.swing.JFrame {

    public MainMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReportPendingEnrollment = new javax.swing.JButton();
        btnReportEnrollmentCourse = new javax.swing.JButton();
        btnReportCurrentEnrollment = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtQueryCourse = new javax.swing.JTextField();
        txtQueryStudent = new javax.swing.JTextField();
        btnQueryStudents = new javax.swing.JButton();
        btnQueryCourses = new javax.swing.JButton();
        txtQueryEnrollment = new javax.swing.JTextField();
        btnQueryEnrollment = new javax.swing.JButton();
        txtQueryRetirement = new javax.swing.JTextField();
        btnQueryRetirement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMantenimiento = new javax.swing.JMenu();
        miStudent = new javax.swing.JMenuItem();
        miCourse = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miEnrollment = new javax.swing.JMenuItem();
        miRetirement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Reporte");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        btnReportPendingEnrollment.setText("Reporte");
        jPanel2.add(btnReportPendingEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, -1));

        btnReportEnrollmentCourse.setText("Reporte");
        jPanel2.add(btnReportEnrollmentCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, -1));

        btnReportCurrentEnrollment.setText("Reporte ");
        jPanel2.add(btnReportCurrentEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, -1));

        jLabel3.setText("Alumnos matriculados por curso");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel4.setText("Alumnos con matrícula pendiente");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel5.setText("Alumnos con matrícula vigente");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 340, 390));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel1.setMinimumSize(new java.awt.Dimension(701, 415));
        jPanel1.setPreferredSize(new java.awt.Dimension(701, 415));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQueryCourse.setText("0");
        jPanel1.add(txtQueryCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        txtQueryStudent.setText("0");
        jPanel1.add(txtQueryStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        btnQueryStudents.setText("Consulta Alumnos");
        jPanel1.add(btnQueryStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 105, 150, -1));

        btnQueryCourses.setText("Consulta Cursos");
        jPanel1.add(btnQueryCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 145, 150, -1));

        txtQueryEnrollment.setText("0");
        jPanel1.add(txtQueryEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        btnQueryEnrollment.setText("Consulta Matrículas");
        jPanel1.add(btnQueryEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 185, 150, -1));

        txtQueryRetirement.setText("0");
        jPanel1.add(txtQueryRetirement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        btnQueryRetirement.setText("Consulta Retiros");
        jPanel1.add(btnQueryRetirement, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 225, 150, -1));

        jLabel1.setText("Consulta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 390));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 720, 420));

        mMantenimiento.setText("Mantenimiento");

        miStudent.setText("Alumno");
        mMantenimiento.add(miStudent);

        miCourse.setText("Curso");
        mMantenimiento.add(miCourse);

        jMenuBar1.add(mMantenimiento);

        jMenu2.setText("Registro");

        miEnrollment.setText("Matrícula");
        jMenu2.add(miEnrollment);

        miRetirement.setText("Retiro");
        jMenu2.add(miRetirement);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        MainMenuController mainMenuController = new MainMenuController(this); //objeto
        mainMenuController.loadStudents();
    }//GEN-LAST:event_formWindowOpened

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnQueryCourses;
    public javax.swing.JButton btnQueryEnrollment;
    public javax.swing.JButton btnQueryRetirement;
    public javax.swing.JButton btnQueryStudents;
    public javax.swing.JButton btnReportCurrentEnrollment;
    public javax.swing.JButton btnReportEnrollmentCourse;
    public javax.swing.JButton btnReportPendingEnrollment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JMenu mMantenimiento;
    public javax.swing.JMenuItem miCourse;
    public javax.swing.JMenuItem miEnrollment;
    public javax.swing.JMenuItem miRetirement;
    public javax.swing.JMenuItem miStudent;
    public javax.swing.JTextField txtQueryCourse;
    public javax.swing.JTextField txtQueryEnrollment;
    public javax.swing.JTextField txtQueryRetirement;
    public javax.swing.JTextField txtQueryStudent;
    // End of variables declaration//GEN-END:variables
}
