
package proyecto.vistas;

import proyecto.controladores.ControladorMenuPrincipal;

public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReporteAlumno = new javax.swing.JButton();
        btnReporteCurso = new javax.swing.JButton();
        btnReporteMatriculas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCursos = new javax.swing.JTextField();
        txtAlumnos = new javax.swing.JTextField();
        btnAlumnos = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        txtMatriculas = new javax.swing.JTextField();
        btnMatriculas = new javax.swing.JButton();
        txtRetiros = new javax.swing.JTextField();
        btnRetiro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMantenimiento = new javax.swing.JMenu();
        miAlumno = new javax.swing.JMenuItem();
        miCurso = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miMatricula = new javax.swing.JMenuItem();
        miRetiro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Reporte");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        btnReporteAlumno.setText("Reporte");
        jPanel2.add(btnReporteAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, -1));

        btnReporteCurso.setText("Reporte");
        jPanel2.add(btnReporteCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, -1));

        btnReporteMatriculas.setText("Reporte ");
        jPanel2.add(btnReporteMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, -1));

        jLabel3.setText("Alumnos matriculados por curso");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel4.setText("Alumnos con matrícula pendiente");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel5.setText("Alumnos con matrícula vigente");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 340, 390));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel1.setMinimumSize(new java.awt.Dimension(701, 415));
        jPanel1.setPreferredSize(new java.awt.Dimension(701, 415));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCursos.setText("0");
        jPanel1.add(txtCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        txtAlumnos.setText("0");
        jPanel1.add(txtAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        btnAlumnos.setText("Consulta Alumnos");
        jPanel1.add(btnAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 105, 150, -1));

        btnCursos.setText("Consulta Cursos");
        jPanel1.add(btnCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 145, 150, -1));

        txtMatriculas.setText("0");
        jPanel1.add(txtMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        btnMatriculas.setText("Consulta Matrículas");
        jPanel1.add(btnMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 185, 150, -1));

        txtRetiros.setText("0");
        jPanel1.add(txtRetiros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        btnRetiro.setText("Consulta Retiros");
        jPanel1.add(btnRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 225, 150, -1));

        jLabel1.setText("Consulta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 390));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 720, 420));

        mMantenimiento.setText("Mantenimiento");

        miAlumno.setText("Alumno");
        mMantenimiento.add(miAlumno);

        miCurso.setText("Curso");
        mMantenimiento.add(miCurso);

        jMenuBar1.add(mMantenimiento);

        jMenu2.setText("Registro");

        miMatricula.setText("Matrícula");
        jMenu2.add(miMatricula);

        miRetiro.setText("Retiro");
        jMenu2.add(miRetiro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ControladorMenuPrincipal controladorMaiMenu = new ControladorMenuPrincipal(this);
    }//GEN-LAST:event_formWindowOpened

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlumnos;
    public javax.swing.JButton btnCursos;
    public javax.swing.JButton btnMatriculas;
    public javax.swing.JButton btnReporteAlumno;
    public javax.swing.JButton btnReporteCurso;
    public javax.swing.JButton btnReporteMatriculas;
    public javax.swing.JButton btnRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JMenu mMantenimiento;
    public javax.swing.JMenuItem miAlumno;
    public javax.swing.JMenuItem miCurso;
    public javax.swing.JMenuItem miMatricula;
    public javax.swing.JMenuItem miRetiro;
    public javax.swing.JTextField txtAlumnos;
    public javax.swing.JTextField txtCursos;
    public javax.swing.JTextField txtMatriculas;
    public javax.swing.JTextField txtRetiros;
    // End of variables declaration//GEN-END:variables
}
